services:
  - type: web
    name: relatorio-equipe
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.14.0
